//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deep.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deep.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;6279529&quot;: [
        ///    {
        ///      &quot;X&quot;: -353.4907,
        ///      &quot;Y&quot;: 10.6484413,
        ///      &quot;Z&quot;: 375.8602
        ///    },
        ///    {
        ///      &quot;X&quot;: -366.9907,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 375.508636
        ///    },
        ///    {
        ///      &quot;X&quot;: -339.9907,
        ///      &quot;Y&quot;: 21.7968826,
        ///      &quot;Z&quot;: 376.211761
        ///    }
        ///  ],
        ///  &quot;6279530&quot;: [
        ///    {
        ///      &quot;X&quot;: -372.857574,
        ///      &quot;Y&quot;: 10.6484413,
        ///      &quot;Z&quot;: 359.499176
        ///    },
        ///    {
        ///      &quot;X&quot;: -373.204468,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 345.999054
        ///    },
        ///    {
        ///      &quot;X&quot;: -372.510681,
        ///      &quot;Y&quot;: 21.7968826,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;6288807&quot;: [
        ///    {
        ///      &quot;X&quot;: -354.49765,
        ///      &quot;Y&quot;: 10.250001,
        ///      &quot;Z&quot;: 227.816116
        ///    },
        ///    {
        ///      &quot;X&quot;: -370.767181,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 225.948914
        ///    },
        ///    {
        ///      &quot;X&quot;: -338.228119,
        ///      &quot;Y&quot;: 21.0000019,
        ///      &quot;Z&quot;: 229.683319
        ///    }
        ///  ],
        ///  &quot;6288808&quot;: [
        ///    {
        ///      &quot;X&quot;: -338.7517,
        ///      &quot;Y&quot;: 10.25,
        ///      &quot;Z&quot;: 244.477966
        ///    },
        ///    {
        ///      &quot;X&quot;: -340.186981,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 228.2519
        ///    },
        ///    {
        ///      &quot;X&quot;: -337.3164,
        ///      &quot;Y&quot;: 21.0,
        ///      &quot;Z&quot;: 2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;6288879&quot;: [
        ///    {
        ///      &quot;X&quot;: -354.49765,
        ///      &quot;Y&quot;: 10.249999,
        ///      &quot;Z&quot;: 227.816116
        ///    },
        ///    {
        ///      &quot;X&quot;: -370.767181,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 225.948914
        ///    },
        ///    {
        ///      &quot;X&quot;: -338.228119,
        ///      &quot;Y&quot;: 20.9999981,
        ///      &quot;Z&quot;: 229.683319
        ///    }
        ///  ],
        ///  &quot;6288880&quot;: [
        ///    {
        ///      &quot;X&quot;: -338.7517,
        ///      &quot;Y&quot;: 10.25,
        ///      &quot;Z&quot;: 244.477966
        ///    },
        ///    {
        ///      &quot;X&quot;: -340.186981,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 228.2519
        ///    },
        ///    {
        ///      &quot;X&quot;: -337.3164,
        ///      &quot;Y&quot;: 21.0,
        ///      &quot;Z&quot;: 2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;6288994&quot;: [
        ///    {
        ///      &quot;X&quot;: -355.65,
        ///      &quot;Y&quot;: 10.750001,
        ///      &quot;Z&quot;: 226.089554
        ///    },
        ///    {
        ///      &quot;X&quot;: -368.306244,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 226.073914
        ///    },
        ///    {
        ///      &quot;X&quot;: -342.993744,
        ///      &quot;Y&quot;: 22.0000019,
        ///      &quot;Z&quot;: 226.1052
        ///    }
        ///  ],
        ///  &quot;6288995&quot;: [
        ///    {
        ///      &quot;X&quot;: -337.087219,
        ///      &quot;Y&quot;: 10.75,
        ///      &quot;Z&quot;: 243.34964
        ///    },
        ///    {
        ///      &quot;X&quot;: -337.0916,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 230.6973
        ///    },
        ///    {
        ///      &quot;X&quot;: -337.082855,
        ///      &quot;Y&quot;: 22.0,
        ///      &quot;Z&quot;: 256.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;6429933&quot;: [
        ///    {
        ///      &quot;X&quot;: -236.0,
        ///      &quot;Y&quot;: 4.75,
        ///      &quot;Z&quot;: 389.992371
        ///    },
        ///    {
        ///      &quot;X&quot;: -243.777344,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 389.992371
        ///    },
        ///    {
        ///      &quot;X&quot;: -228.222656,
        ///      &quot;Y&quot;: 10.0,
        ///      &quot;Z&quot;: 389.992371
        ///    }
        ///  ],
        ///  &quot;6429960&quot;: [
        ///    {
        ///      &quot;X&quot;: -218.007629,
        ///      &quot;Y&quot;: 4.75,
        ///      &quot;Z&quot;: 368.006226
        ///    },
        ///    {
        ///      &quot;X&quot;: -218.010315,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 360.228882
        ///    },
        ///    {
        ///      &quot;X&quot;: -218.004929,
        ///      &quot;Y&quot;: 10.0,
        ///      &quot;Z&quot;: 375.783569        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;6425252&quot;: [
        ///    {
        ///      &quot;X&quot;: -357.792969,
        ///      &quot;Y&quot;: 10.078125,
        ///      &quot;Z&quot;: 225.207031
        ///    },
        ///    {
        ///      &quot;X&quot;: -368.5547,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 223.765625
        ///    },
        ///    {
        ///      &quot;X&quot;: -347.03125,
        ///      &quot;Y&quot;: 20.65625,
        ///      &quot;Z&quot;: 226.648438
        ///    }
        ///  ],
        ///  &quot;6425253&quot;: [
        ///    {
        ///      &quot;X&quot;: -374.8202,
        ///      &quot;Y&quot;: 5.96484375,
        ///      &quot;Z&quot;: 241.669968
        ///    },
        ///    {
        ///      &quot;X&quot;: -376.769257,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 230.822983
        ///    },
        ///    {
        ///      &quot;X&quot;: -372.871155,
        ///      &quot;Y&quot;: 12.4296875,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;6418711&quot;: [
        ///    {
        ///      &quot;X&quot;: -299.75,
        ///      &quot;Y&quot;: 5.0,
        ///      &quot;Z&quot;: 246.0
        ///    },
        ///    {
        ///      &quot;X&quot;: -300.0,
        ///      &quot;Y&quot;: 0.0,
        ///      &quot;Z&quot;: 245.5
        ///    },
        ///    {
        ///      &quot;X&quot;: -299.5,
        ///      &quot;Y&quot;: 10.0,
        ///      &quot;Z&quot;: 246.5
        ///    }
        ///  ],
        ///  &quot;6418712&quot;: [
        ///    {
        ///      &quot;X&quot;: -300.25,
        ///      &quot;Y&quot;: 5.0,
        ///      &quot;Z&quot;: 246.0
        ///    },
        ///    {
        ///      &quot;X&quot;: -300.5,
        ///      &quot;Y&quot;: 0.0,
        ///      &quot;Z&quot;: 245.5
        ///    },
        ///    {
        ///      &quot;X&quot;: -300.0,
        ///      &quot;Y&quot;: 10.0,
        ///      &quot;Z&quot;: 246.5
        ///    }
        ///  ],
        ///  &quot;6418713&quot;: [
        ///    {
        ///      &quot;X&quot;: -299.75,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;6434642&quot;: [
        ///    {
        ///      &quot;X&quot;: -371.236084,
        ///      &quot;Y&quot;: 4.75,
        ///      &quot;Z&quot;: 243.524841
        ///    },
        ///    {
        ///      &quot;X&quot;: -372.660156,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 227.297791
        ///    },
        ///    {
        ///      &quot;X&quot;: -369.811981,
        ///      &quot;Y&quot;: 10.0,
        ///      &quot;Z&quot;: 259.7519
        ///    }
        ///  ],
        ///  &quot;6434641&quot;: [
        ///    {
        ///      &quot;X&quot;: -355.4898,
        ///      &quot;Y&quot;: 4.77734375,
        ///      &quot;Z&quot;: 260.175476
        ///    },
        ///    {
        ///      &quot;X&quot;: -371.759338,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 258.308319
        ///    },
        ///    {
        ///      &quot;X&quot;: -339.220276,
        ///      &quot;Y&quot;: 10.0546875,
        ///      &quot;Z&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;6441757&quot;: [
        ///    {
        ///      &quot;X&quot;: -371.236084,
        ///      &quot;Y&quot;: 4.75,
        ///      &quot;Z&quot;: 243.524841
        ///    },
        ///    {
        ///      &quot;X&quot;: -372.660156,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 227.297791
        ///    },
        ///    {
        ///      &quot;X&quot;: -369.811981,
        ///      &quot;Y&quot;: 10.0,
        ///      &quot;Z&quot;: 259.7519
        ///    }
        ///  ],
        ///  &quot;6441756&quot;: [
        ///    {
        ///      &quot;X&quot;: -355.4898,
        ///      &quot;Y&quot;: 4.77734375,
        ///      &quot;Z&quot;: 260.175476
        ///    },
        ///    {
        ///      &quot;X&quot;: -371.759338,
        ///      &quot;Y&quot;: -0.5,
        ///      &quot;Z&quot;: 258.308319
        ///    },
        ///    {
        ///      &quot;X&quot;: -339.220276,
        ///      &quot;Y&quot;: 10.0546875,
        ///      &quot;Z&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit fields are not supported..
        /// </summary>
        public static string BitFieldsNotSupported {
            get {
                return ResourceManager.GetString("BitFieldsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿[
        ///  {
        ///    &quot;Index&quot;: 1,
        ///    &quot;Name&quot;: &quot;the Palace of the Dead&quot;,
        ///    &quot;NameWithoutArticle&quot;: &quot;Palace of the Dead&quot;,
        ///    &quot;ContentFinderId&quot;: 174,
        ///    &quot;PomanderMapping&quot;: {
        ///      &quot;1&quot;: 0,
        ///      &quot;2&quot;: 1,
        ///      &quot;3&quot;: 2,
        ///      &quot;4&quot;: 3,
        ///      &quot;5&quot;: 4,
        ///      &quot;6&quot;: 5,
        ///      &quot;7&quot;: 6,
        ///      &quot;8&quot;: 7,
        ///      &quot;9&quot;: 8,
        ///      &quot;10&quot;: 9,
        ///      &quot;11&quot;: 10,
        ///      &quot;12&quot;: 11,
        ///      &quot;13&quot;: 12,
        ///      &quot;14&quot;: 13,
        ///      &quot;15&quot;: 14,
        ///      &quot;16&quot;: 15
        ///    },
        ///    &quot;LobbyId&quot;: 570,
        ///    &quot;UnlockQuest&quot;: 67092,
        ///    &quot;Npc&quot;: {
        ///      &quot;Location&quot;: [
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeepDungeonData {
            get {
                return ResourceManager.GetString("DeepDungeonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EnumType property is not specified..
        /// </summary>
        public static string EnumTypeNotSet {
            get {
                return ResourceManager.GetString("EnumTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested value &apos;{0}&apos; was not found..
        /// </summary>
        public static string EnumValueNotFound {
            get {
                return ResourceManager.GetString("EnumValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: 4551,
        ///    &quot;Level&quot;: 0,
        ///    &quot;Rate&quot;: [ 0.32, 0.4 ],
        ///    &quot;Max&quot;:  [160, 200]
        ///  },
        ///  {
        ///    &quot;Id&quot;: 4552,
        ///    &quot;Level&quot;: 20,
        ///    &quot;Rate&quot;: [ 0.32, 0.4 ],
        ///    &quot;Max&quot;: [ 340, 440 ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: 4553,
        ///    &quot;Level&quot;: 30,
        ///    &quot;Rate&quot;: [ 0.28, 0.35 ],
        ///    &quot;Max&quot;: [ 660, 840 ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: 4554,
        ///    &quot;Level&quot;: 40,
        ///    &quot;Rate&quot;: [ 0.24, 0.30 ],
        ///    &quot;Max&quot;: [ 1040, 1300 ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: 13637,
        ///    &quot;Level&quot;: 50,
        ///    &quot;Rate&quot;: [ 0.24, 0.30 ],
        ///    &quot;Max&quot;: [ 1920, 2400 ]
        ///  }
        ///].
        /// </summary>
        public static string pots {
            get {
                return ResourceManager.GetString("pots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target type must extend &apos;{0}&apos;..
        /// </summary>
        public static string TargetNotExtendingType {
            get {
                return ResourceManager.GetString("TargetNotExtendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has no standard values..
        /// </summary>
        public static string TypeHasNoStandardValues {
            get {
                return ResourceManager.GetString("TypeHasNoStandardValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aether: .
        /// </summary>
        public static string UI_Aether {
            get {
                return ResourceManager.GetString("UI_Aether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Combat Routine.
        /// </summary>
        public static string UI_ChangeCR {
            get {
                return ResourceManager.GetString("UI_ChangeCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat.
        /// </summary>
        public static string UI_Combat {
            get {
                return ResourceManager.GetString("UI_Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot will start combat with mobs within {0:##}y.
        /// </summary>
        public static string UI_CombatReach {
            get {
                return ResourceManager.GetString("UI_CombatReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactName.
        /// </summary>
        public static string UI_ContactInfo {
            get {
                return ResourceManager.GetString("UI_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Verbose Logging.
        /// </summary>
        public static string UI_EnableVerboseLogging {
            get {
                return ResourceManager.GetString("UI_EnableVerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        public static string UI_ErrorReport {
            get {
                return ResourceManager.GetString("UI_ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string UI_Floor {
            get {
                return ResourceManager.GetString("UI_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} - {1}.
        /// </summary>
        public static string UI_FloorSettingRow {
            get {
                return ResourceManager.GetString("UI_FloorSettingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always try to pick up &apos;Cache of the Horde&apos; when prioritizing the exit.
        /// </summary>
        public static string UI_GoForTheHoard {
            get {
                return ResourceManager.GetString("UI_GoForTheHoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use HP Pot at {0}%.
        /// </summary>
        public static string UI_HPPOT {
            get {
                return ResourceManager.GetString("UI_HPPOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am in a party! I Expect this person to start the dungeon:.
        /// </summary>
        public static string UI_IAmInAParty {
            get {
                return ResourceManager.GetString("UI_IAmInAParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Describe your issue.
        /// </summary>
        public static string UI_IssueBody {
            get {
                return ResourceManager.GetString("UI_IssueBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Created Your issue id is in the log. Please use that when you ask for help in discord.
        /// </summary>
        public static string UI_IssueCreated {
            get {
                return ResourceManager.GetString("UI_IssueCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Issue.
        /// </summary>
        public static string UI_IssueSubmit {
            get {
                return ResourceManager.GetString("UI_IssueSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Title.
        /// </summary>
        public static string UI_IssueTitle {
            get {
                return ResourceManager.GetString("UI_IssueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Title cannot be empty.
        /// </summary>
        public static string UI_IssueTitleEmpty {
            get {
                return ResourceManager.GetString("UI_IssueTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Dive Key:.
        /// </summary>
        public static string UI_KeyBox {
            get {
                return ResourceManager.GetString("UI_KeyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Retreat.
        /// </summary>
        public static string UI_MeleeRetreat {
            get {
                return ResourceManager.GetString("UI_MeleeRetreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mimic Chests.
        /// </summary>
        public static string UI_Mimics {
            get {
                return ResourceManager.GetString("UI_Mimics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize the Exit.
        /// </summary>
        public static string UI_OpenAllChests {
            get {
                return ResourceManager.GetString("UI_OpenAllChests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- That&apos;s me.
        /// </summary>
        public static string UI_PartyLeaderMe {
            get {
                return ResourceManager.GetString("UI_PartyLeaderMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- That&apos;s Not Me.
        /// </summary>
        public static string UI_PartyLeaderNotMe {
            get {
                return ResourceManager.GetString("UI_PartyLeaderNotMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Private Issue.
        /// </summary>
        public static string UI_PrivateIssue {
            get {
                return ResourceManager.GetString("UI_PrivateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Party Information.
        /// </summary>
        public static string UI_RefreshParty {
            get {
                return ResourceManager.GetString("UI_RefreshParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to do more than floor 10 solo.
        ///I know the bot will fail..
        /// </summary>
        public static string UI_RunAnyFloor {
            get {
                return ResourceManager.GetString("UI_RunAnyFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Pomander of Steel for Boss.
        /// </summary>
        public static string UI_SavePomSteel {
            get {
                return ResourceManager.GetString("UI_SavePomSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Pomander of Strength for Boss.
        /// </summary>
        public static string UI_SavePomStr {
            get {
                return ResourceManager.GetString("UI_SavePomStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string UI_SaveSlot_1 {
            get {
                return ResourceManager.GetString("UI_SaveSlot_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string UI_SaveSlot_2 {
            get {
                return ResourceManager.GetString("UI_SaveSlot_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Dungeon Settings (V: {0}).
        /// </summary>
        public static string UI_SettingsTitle {
            get {
                return ResourceManager.GetString("UI_SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Silver Chests.
        /// </summary>
        public static string UI_Silver {
            get {
                return ResourceManager.GetString("UI_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at floor 51.
        /// </summary>
        public static string UI_StartAT51 {
            get {
                return ResourceManager.GetString("UI_StartAT51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop after current run.
        /// </summary>
        public static string UI_STOP {
            get {
                return ResourceManager.GetString("UI_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop the bot before creating an error report. .
        /// </summary>
        public static string UI_STOPBOT {
            get {
                return ResourceManager.GetString("UI_STOPBOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop after this floors Aether value has been reached..
        /// </summary>
        public static string UI_StopCheckBox {
            get {
                return ResourceManager.GetString("UI_StopCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest Settings.
        /// </summary>
        public static string UI_TabChests {
            get {
                return ResourceManager.GetString("UI_TabChests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Settings.
        /// </summary>
        public static string UI_TabFloor {
            get {
                return ResourceManager.GetString("UI_TabFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string UI_TabGeneral {
            get {
                return ResourceManager.GetString("UI_TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string UI_TabKey {
            get {
                return ResourceManager.GetString("UI_TabKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Trap Chests.
        /// </summary>
        public static string UI_Traps {
            get {
                return ResourceManager.GetString("UI_Traps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Antidote (when Available).
        /// </summary>
        public static string UI_UseAntidote {
            get {
                return ResourceManager.GetString("UI_UseAntidote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Echo Drops (when Available).
        /// </summary>
        public static string UI_UseEchoDrops {
            get {
                return ResourceManager.GetString("UI_UseEchoDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Pomander Of Alteration.
        /// </summary>
        public static string UI_UsePomAlteration {
            get {
                return ResourceManager.GetString("UI_UsePomAlteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Pomander of Rage.
        /// </summary>
        public static string UI_UsePomRage {
            get {
                return ResourceManager.GetString("UI_UsePomRage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Save Slot:.
        /// </summary>
        public static string UI_UseSaveSlot {
            get {
                return ResourceManager.GetString("UI_UseSaveSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Sustain Pot.
        /// </summary>
        public static string UI_UseSustain {
            get {
                return ResourceManager.GetString("UI_UseSustain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Issues.
        /// </summary>
        public static string UI_View_Issues {
            get {
                return ResourceManager.GetString("UI_View_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be of type &apos;{0}&apos;..
        /// </summary>
        public static string ValueNotOfType {
            get {
                return ResourceManager.GetString("ValueNotOfType", resourceCulture);
            }
        }
    }
}
